name       : ksshaskpass
version    : 5.12.5
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.5/ksshaskpass-5.12.5.tar.xz : c41b3c18fd093a885deed90fe9d67e19920876fbed82d8bb108e36c712b8f86d
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kwallet-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
