name       : ksshaskpass
version    : 5.18.2
release    : 45
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.2/ksshaskpass-5.18.2.tar.xz : d3456e02a3779e66907459319dffb780e3e780e3bbfdcc686b2dfb7d81caf74f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kwallet-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
