name       : ksshaskpass
version    : 5.11.4
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.4/ksshaskpass-5.11.4.tar.xz : 7de555ebd3ea98e57adea7261e276e2bbdf155e2527e07039eb5f01ae9e61ff3
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kwallet-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
