name       : ksshaskpass
version    : 5.15.5
release    : 32
source     :
    - https://download.kde.org/stable/plasma/5.15.5/ksshaskpass-5.15.5.tar.xz : 4b6eae3b594480f6265843fa0b2f3d2051fd45894d27eee3681b7b33c4f52e7e
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kwallet-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
