name       : ksshaskpass
version    : 5.12.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.3/ksshaskpass-5.12.3.tar.xz : f0bc3f83952fd71d3bb0cd79f6c810d4d3357c79d4c71e3cec35c41bc2588f87
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kwallet-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
