name       : ksshaskpass
version    : 5.17.3
release    : 41
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.3/ksshaskpass-5.17.3.tar.xz : 5a5c4f78808ebc0272abaaff03aa9a89928740348b0f7c735761a1fa334ca81f
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kwallet-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
