name       : ksshaskpass
version    : 5.11.0
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.11.0/ksshaskpass-5.11.0.tar.xz : e01a97c937e275db5695b1ab0066cdb8bfda5dbe2a03222a9561ab25ffdeccda
license    : GPL-2.0
component  : desktop.kde.core
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kwallet-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
